dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
services:
  - mongodb
  - redis-server
before_install:
  - pip install --upgrade pip setuptools
install:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install "tinydb<4"; fi
  - pip install -r requirements.txt
  - pip install -r extra.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
env:
  - ADAPTER=mongo HTTPBIN=httpbin.bemisc.com
  - ADAPTER=tiny HTTPBIN=httpbin.bemisc.com
script: coverage run --source=appier setup.py test
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: gB8Q3pfyoV43szD8+BCaoRWr7L2Iu2ONm2fyNcfz4p2+t8ez/vSWZZenUOfb5DJELli6LyUKzQDo/PqeEpcwhyW4p0/zrz8BqaVZoZpJ8Y0Vh1YH32Tp4tizcdA6XtY5CQhD5YawzhblSY9NQYAmZZ524bXGFLQ6pPMrNW0/bDg=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
    condition: $ADAPTER = mongo
